### PR TITLE
Make imgFallback if provided as a function can override img src value.

### PR DESCRIPTION
**Pull request by entertainyou**

### CODE REVIEW

**Comment by Tjatse** [comment]
Thanks, sounds more convenient and I'll review it this weekend ;)

**Comment by entertainyou** [comment]
@Tjatse , I've submit other patches, please also review them when you have time, :)

**Comment by entertainyou** [comment]
ping, @Tjatse

**Comment by Tjatse** [comment]
Pong!!!
Just got back, reviewing, sorry for the delay.

**Comment by entertainyou** [comment]
:) Me too.

**Pull request merged**
