### PR TITLE
Add a option imgFallback which use img element's data-src attribute when

### PR DESCRIPTION
**Pull request by entertainyou**
src attribute is missing.

### CODE REVIEW

**Comment by Tjatse** [comment]
Appreciates! It's a good solution to solve some initial problems.
But in some situations like following:
```html
<img data-src-origin="my-pic.jpg" data-src-thumbnail="my-pic-50x50.jpg" />
```
It can not work any more, so how about define the `imgFallback` could be one of following types:
- **Boolean** Get the source of image by `node.data('src')` instead of `node.attr('src')`.
- **String** Get the source of image by `imgFallback`, e.g.:
  - *data-src-xxx*: 'node.data('src-xxx')`.
  - *prop-src-xxx*: 'node.prop('src-xxx')`.
  - *src-xxx*: 'node.attr('src-xxx')`.
- **Function** Get the source of image by `imgFallback(node)`, e.g.:

  ```javascript
  {
    imgFallback: function(node){
      return node.attr('base') + '/' + node.attr('rel-path');
    }
  }
  ```

What do yo say?

**Comment by entertainyou** [comment]
I'll update the PR. Just to make sure, what you suggested is only applicable when src attribute is missing, right?

**Comment by entertainyou** [comment]
Pushed the update, and cheerio does not support .prop function, so only data-xxx or actual attribute is supported.

**Comment by Tjatse** [comment]
Merged, thanks!

**Pull request merged**
