### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by miduga**
As stated on #33, we’ve to fix the documentation for promises.

### CODE REVIEW

**Comment by Tjatse** [comment]
I'll review these ASAP.
Thx, dude, I appreciate it.

**Comment by Tjatse** [comment]
Thanks for your patience, just could not get time off work to checkout these stuff.
I'll start it on this weekend. :)

**Comment by Tjatse** [comment]
Released, Thanks a lot.
[History](https://github.com/Tjatse/node-readability/blob/master/HISTORY.md)

**Comment by miduga** [comment]
Thanks to you!

**Pull request merged**
